package net.redstonecraft.vulkan.vk.enums

import org.lwjgl.vulkan.VK13.*

enum class InputRate(val inputRate: Int) {
    VERTEX(VK_VERTEX_INPUT_RATE_VERTEX),
    INSTANCE(VK_VERTEX_INPUT_RATE_INSTANCE)
}

enum class VulkanCulling(val cullMode: Int) {
    OFF(VK_CULL_MODE_NONE), FRONT(VK_CULL_MODE_FRONT_BIT), BACK(VK_CULL_MODE_BACK_BIT), BOTH(VK_CULL_MODE_FRONT_AND_BACK)
}

enum class VulkanPrimitive(val primitive: Int) {
    POINT(VK_PRIMITIVE_TOPOLOGY_POINT_LIST),
    LINE(VK_PRIMITIVE_TOPOLOGY_LINE_LIST), LINE_STRIP(VK_PRIMITIVE_TOPOLOGY_LINE_STRIP),
    TRIANGLE(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST), TRIANGLE_STRIP(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP)
}

enum class VulkanAttachmentLoadOp(val loadOp: Int) {
    LOAD(VK_ATTACHMENT_LOAD_OP_LOAD),
    CLEAR(VK_ATTACHMENT_LOAD_OP_CLEAR),
    DONT_CARE(VK_ATTACHMENT_LOAD_OP_DONT_CARE)
}
