package net.redstonecraft.vulkan.vk.enums

import org.lwjgl.vulkan.VK12.*

enum class VulkanPrimitive(val primitive: Int) {
    POINT(VK_PRIMITIVE_TOPOLOGY_POINT_LIST),
    LINE(VK_PRIMITIVE_TOPOLOGY_LINE_LIST), LINE_STRIP(VK_PRIMITIVE_TOPOLOGY_LINE_STRIP),
    TRIANGLE(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST), TRIANGLE_STRIP(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP)
}
